version: '3.7'
services:
  bert:
    container_name: bert-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    working_dir: /app
    stdin_open: true
    tty: true 